add role instance and revert docker back
Signed-off-by: weisonweileen <weisonweileen@gmail.com>

diff --git a/.github/workflows/premerge-ci.yml b/.github/workflows/premerge-ci.yml
--- a/.github/workflows/premerge-ci.yml
+++ b/.github/workflows/premerge-ci.yml
@@ -107,105 +107,105 @@
             --instance-os-user $EC2_USER_NAME
 
 
-      - name: Verify credentials inside instance
-        run: |
-          echo "====Verify credentials inside instance...===="
-          set -euo pipefail
-          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP \
-            "aws sts get-caller-identity"
-        env:
-          EC2_IP: ${{ env.EC2_IP }}
-      ############# Build #############
-      # - name: build
+      # - name: Verify credentials inside instance
       #   run: |
-      #     echo "====Copying source code...===="
-      #     wait_time=$RETRY_WAIT_TIME
-      #     SRC_DIR=$(basename $GITHUB_WORKSPACE)
-      #     echo ""====Check environment variables..."===="
-      #     echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
-      #     echo "CODEBUILD_SRC_DIR=$CODEBUILD_SRC_DIR"
-      #     echo "EC2_USER_NAME=$EC2_USER_NAME"
-      #     echo "SRC_DIR=$SRC_DIR"
-      #     echo "RETRY_WAIT_TIME=$RETRY_WAIT_TIME"
-      #     echo "MAX_RETRIES=$MAX_RETRIES"
-      #     echo "====Repo file check...===="
-      #     ls ./
+      #     echo "====Verify credentials inside instance...===="
+      #     set -euo pipefail
+      #     ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP \
+      #       "aws sts get-caller-identity"
+      #   env:
+      #     EC2_IP: ${{ env.EC2_IP }}
+      ############# Build #############
+      - name: build
+        run: |
+          echo "====Copying source code...===="
+          wait_time=$RETRY_WAIT_TIME
+          SRC_DIR=$(basename $GITHUB_WORKSPACE)
+          echo ""====Check environment variables..."===="
+          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
+          echo "CODEBUILD_SRC_DIR=$CODEBUILD_SRC_DIR"
+          echo "EC2_USER_NAME=$EC2_USER_NAME"
+          echo "SRC_DIR=$SRC_DIR"
+          echo "RETRY_WAIT_TIME=$RETRY_WAIT_TIME"
+          echo "MAX_RETRIES=$MAX_RETRIES"
+          echo "====Repo file check...===="
+          ls ./
 
 
-      #     retry_count=0
+          retry_count=0
 
-      #     # change to parent directory t
-      #     cd ..
+          # change to parent directory t
+          cd ..
 
-      #     while [ $retry_count -lt $MAX_RETRIES ]; do
-      #       if [ $retry_count -gt 0 ]; then
-      #         wait_time=$((wait_time * 2))
-      #         echo "Retry attempt $((retry_count + 1))/$MAX_RETRIES. Waiting $wait_time seconds..."
-      #         sleep $wait_time
-      #       fi
+          while [ $retry_count -lt $MAX_RETRIES ]; do
+            if [ $retry_count -gt 0 ]; then
+              wait_time=$((wait_time * 2))
+              echo "Retry attempt $((retry_count + 1))/$MAX_RETRIES. Waiting $wait_time seconds..."
+              sleep $wait_time
+            fi
 
-      #       if scp -o ConnectTimeout=10 -o StrictHostKeyChecking=no -r $SRC_DIR ubuntu@$EC2_INSTANCE_IP:~; then
-      #         echo "SCP command succeeded"
-      #         break
-      #       fi
+            if scp -o ConnectTimeout=10 -o StrictHostKeyChecking=no -r $SRC_DIR ubuntu@$EC2_INSTANCE_IP:~; then
+              echo "SCP command succeeded"
+              break
+            fi
 
-      #       retry_count=$((retry_count + 1))
-      #     done
+            retry_count=$((retry_count + 1))
+          done
 
-      #     if [ $retry_count -eq $MAX_RETRIES ]; then
-      #       echo "SCP command failed after $MAX_RETRIES attempts"
-      #       exit 1
-      #     fi
+          if [ $retry_count -eq $MAX_RETRIES ]; then
+            echo "SCP command failed after $MAX_RETRIES attempts"
+            exit 1
+          fi
 
-      #     echo "====Running tests on EC2 instance...===="
-      #     ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no $EC2_USER_NAME@$EC2_INSTANCE_IP "
+          echo "====Running tests on EC2 instance...===="
+          ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no $EC2_USER_NAME@$EC2_INSTANCE_IP "
 
-      #       set -euo pipefail
+            set -euo pipefail
 
-      #       # Configure BuildKit environment
-      #       export DOCKER_BUILDKIT=1
-      #       export BUILDKIT_INLINE_CACHE=1
+            # Configure BuildKit environment
+            export DOCKER_BUILDKIT=1
+            export BUILDKIT_INLINE_CACHE=1
 
-      #       docker buildx create --name metasim-builder --driver docker-container \
-      #         --driver-opt env.AWS_REGION=$REGION \
-      #         --driver-opt env.AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
-      #         --driver-opt env.AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
-      #         --bootstrap
-      #       docker buildx use metasim-builder
+            docker buildx create --name metasim-builder --driver docker-container \
+              --driver-opt env.AWS_REGION=$REGION \
+              --driver-opt env.AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
+              --driver-opt env.AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
+              --bootstrap
+            docker buildx use metasim-builder
 
-      #       cd \"\$HOME/${SRC_DIR}\"
+            cd \"\$HOME/${SRC_DIR}\"
 
-      #       # docker build
-      #       docker buildx build --progress=plain --platform linux/amd64 -t metasim \
-      #       --cache-from type=s3,region=$REGION,bucket=$CACHE_BUCKET,mode=max \
-      #       --cache-to   type=s3,region=$REGION,bucket=$CACHE_BUCKET,mode=max,ignore-error=true \
-      #       --build-arg DOCKER_UID=1000 \
-      #       --build-arg DOCKER_GID=1000 \
-      #       --build-arg DOCKER_USER=ubuntu \
-      #       -f Dockerfile \
-      #       --load .
-      #       # --cache-to type=s3,region=$REGION,bucket=$CACHE_BUCKET,mode=max,ignore-error=true \
-      #       # --cache-from type=registry,ref=$AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY:latest \
+            # docker build
+            docker buildx build --progress=plain --platform linux/amd64 -t metasim \
+            --cache-from type=s3,region=$REGION,bucket=$CACHE_BUCKET,mode=max \
+            --cache-to   type=s3,region=$REGION,bucket=$CACHE_BUCKET,mode=max,ignore-error=true \
+            --build-arg DOCKER_UID=1000 \
+            --build-arg DOCKER_GID=1000 \
+            --build-arg DOCKER_USER=ubuntu \
+            -f Dockerfile \
+            --load .
+            # --cache-to type=s3,region=$REGION,bucket=$CACHE_BUCKET,mode=max,ignore-error=true \
+            # --cache-from type=registry,ref=$AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPOSITORY:latest \
 
-      #       # run all test
-      #       docker run --rm --entrypoint bash --runtime=nvidia --network=host \
-      #       --name metasim-autotest \
-      #       --user 1000:1000 --privileged \
-      #       -e LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu \
-      #       -e ACCEPT_EULA=Y -e PRIVACY_CONSENT=Y -e OMNI_KIT_ACCEPT_EULA=YES \
-      #       -v /usr/local/cuda:/usr/local/cuda \
-      #       -v "$(pwd)":/home/ubuntu/RoboVerse \
-      #       metasim:latest \
-      #       -c "/home/ubuntu/conda/envs/metasim/bin/python3 -u metasim/test/state_consistency.py --sim isaaclab --headless" \
-      #       || TEST_EXIT_CODE=$?
+            # run all test
+            docker run --rm --entrypoint bash --runtime=nvidia --network=host \
+            --name metasim-autotest \
+            --user 1000:1000 --privileged \
+            -e LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu \
+            -e ACCEPT_EULA=Y -e PRIVACY_CONSENT=Y -e OMNI_KIT_ACCEPT_EULA=YES \
+            -v /usr/local/cuda:/usr/local/cuda \
+            -v "$(pwd)":/home/ubuntu/RoboVerse \
+            metasim:latest \
+            -c "/home/ubuntu/conda/envs/metasim/bin/python3 -u metasim/test/state_consistency.py --sim isaaclab --headless" \
+            || TEST_EXIT_CODE=$?
 
-      #       echo "Test exit code: $TEST_EXIT_CODE" > ~/$SRC_DIR/test_exit_code.txt
-      #     " || { echo "Test execution failed"; exit 1; }
+            echo "Test exit code: $TEST_EXIT_CODE" > ~/$SRC_DIR/test_exit_code.txt
+          " || { echo "Test execution failed"; exit 1; }
 
-      #     if [ "$(cat $CODEBUILD_SRC_DIR/test_exit_code.txt)" != "0" ]; then
-      #       echo "Tests failed with exit code $(cat $CODEBUILD_SRC_DIR/test_exit_code.txt)"
-      #       exit 1
-      #     fi
+          if [ "$(cat $CODEBUILD_SRC_DIR/test_exit_code.txt)" != "0" ]; then
+            echo "Tests failed with exit code $(cat $CODEBUILD_SRC_DIR/test_exit_code.txt)"
+            exit 1
+          fi
 
       ########### Postbuild ##########
       - name: post_build
